### ISSUE TITLE
Cropping of Image 

### ISSUE THREAD

**Issue by ion05** [Technogic/Website#10]
![image](https://user-images.githubusercontent.com/49789627/89758403-5116f580-db05-11ea-8ec8-390bcc54e339.png)

The image needs to be cropped to size about below. 
![image](https://user-images.githubusercontent.com/49789627/89758432-64c25c00-db05-11ea-8d88-5d1238c7040b.png)

**Comment by yuvraajnarula** [comment]
measurements are same

**Comment by ion05** [comment]
I mean there is too much blank space. And decrease K2Tech ka size. It is too intimidating

**Comment by ion05** [comment]
And increase tagline ka size

**Comment by GobindAnand** [comment]
> I mean there is too much blank space. And decrease K2Tech ka size. It is too intimidating

size is fine; img will have to see

**Comment by ion05** [comment]
Tagline is too small and name us too big; It looks intimidating
